version : "3.9"
services:
    db:
        container_name: db-deathnote
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - ./db-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: deathnote_db
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel1234
        networks:
            - net-deathnote
    web:
        container_name: web-deathnote
        depends_on:
            - db
        ports:
            - "8082:80"
        volumes:
            - "./:/var/www/html"
            - "./httpd.conf:/etc/httpd/conf/httpd.conf"
        image: laravel-deathnote
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - net-deathnote
networks:
    net-deathnote:
        
